import { Injectable } from '@angular/core';
import { IZooSmallComponent } from '../../interfaces/zoointerface/zoointerface'
@Injectable({
  providedIn: 'root'
})
export class ZooserviceService {
  zoos: IZooSmallComponent[] = [
    {
      id:11,
      imgUrl: "./assets/image/aa.jpg",
      name: "ُEgypt Zoo",
      address: "Porto Blvd, Suite 100 Los Angeles/CA",
      phone: 12345678910,
      email: "Zooo@mail.com",
      addressUrl: "(view directions)",
      locImg: "./assets/image/pin.png",
      animals:"Giraffes",
      sliderimage1:"./assets/image/s7.jpg",
      sliderimage2:"./assets/image/s5.jpg",
      sliderimage3:"./assets/image/s2.jpg",
      description:"The biggest zoo in egypt has alot of animals like lions ...",
      showimg:"./assets/image/show1.jpg",
      showdescription:"Visita il Delfinario di Dubai per ammirare i graziosi delfini dal naso a bottiglia e le foche che giocano durante gli spettacoli d'animazione. Scegli tra il biglietto standard e quello VIP...",
      showname:"splach safari show",
      upshowdescription:"In the heart of the Burmese rainforest is where some elephants feel right at home. In this unique show, uncover the rare sight of these magnificent animals at work and play in their rainforest habitat alongside their mahouts.",
      upshowname:"Elephants at Work and Play Show",
      upshowdate:"5:00 PM",
      showdate:"6:00 PM",
      upshowloc:"Egypt",
      showloc:"Egypt",
      newsname:"Wild Animals Go Missing at a Zoo, Stirring Fears",
      newsdescription:"The animals briefly slipped their enclosures after heavy flooding at a German zoo — prompting a call for residents to stay indoors. One animal, a bear, was shot dead.",
      newsimg:"./assets/image/news.jpg",
      writer:"JOHN DOE",
      newsdate:" NOV 18",
      newsname1:"Wild Animals Go Missing at a Zoo, Stirring Fears",
      newsdescription1:"The animals briefly slipped their enclosures after heavy flooding at a German zoo — prompting a call for residents to stay indoors. One animal, a bear, was shot dead.",
      newsimg1:"./assets/image/news1.jpg",
      writer1:"JOHN DOE",
      newsdate1:" NOV 19",
      newsname2:"Wild Animals Go Missing at a Zoo, Stirring Fears",
      newsdescription2:"The animals briefly slipped their enclosures after heavy flooding at a German zoo — prompting a call for residents to stay indoors. One animal, a bear, was shot dead.",
      newsimg2:"./assets/image/news2.jpg",
      writer2:"JOHN DOE",
      newsdate2:" NOV 20"
      
      
      
      
     



    },
    {
      id:12,
      imgUrl: "./assets/image/dd.jpg",
      name: "Gizaa Zoo",
      address: "Porto Blvd, Suite 100 Los Angeles/CA",
      phone: 12345678910,
      email: "Zooo@mail.com",
      addressUrl: "(view directions)",
      locImg: "./assets/image/pin.png",
      animals:"Elephants",
      sliderimage1:"./assets/image/s2.jpg",
      sliderimage2:"./assets/image/s1.jpg",
      sliderimage3:"./assets/image/s3.jpg",
      description:"The biggest zoo in egypt has alot of animals like lions ...",
      showimg:"./assets/image/show2.jpg",
      showdescription:"Visita il Delfinario di Dubai per ammirare i graziosi delfini dal naso a bottiglia e le foche che giocano durante gli spettacoli d'animazione. Scegli tra il biglietto standard e quello VIP...",
      showname:"Animal Friends Show",
      upshowdescription:"In the heart of the Burmese rainforest is where some elephants feel right at home. In this unique show, uncover the rare sight of these magnificent animals at work and play in their rainforest habitat alongside their mahouts.",
      upshowname:"Elephants at Work and Play Show",
      upshowdate:"5:00 PM",
      showdate:"6:00 PM",
      upshowloc:"Egypt",
      showloc:"Egypt",
      newsname:"Wild Animals Go Missing at a Zoo, Stirring Fears",
      newsdescription:"The animals briefly slipped their enclosures after heavy flooding at a German zoo — prompting a call for residents to stay indoors. One animal, a bear, was shot dead.",
      newsimg:"./assets/image/news4.jpg",
      writer:"JOHN DOE",
      newsdate:" NOV 18",
      newsname1:"Wild Animals Go Missing at a Zoo, Stirring Fears",
      newsdescription1:"The animals briefly slipped their enclosures after heavy flooding at a German zoo — prompting a call for residents to stay indoors. One animal, a bear, was shot dead.",
      newsimg1:"./assets/image/news5.jpg",
      writer1:"JOHN DOE",
      newsdate1:" NOV 19",
      newsname2:"Wild Animals Go Missing at a Zoo, Stirring Fears",
      newsdescription2:"The animals briefly slipped their enclosures after heavy flooding at a German zoo — prompting a call for residents to stay indoors. One animal, a bear, was shot dead.",
      newsimg2:"./assets/image/news6.jpg",
      writer2:"JOHN DOE",
      newsdate2:" NOV 20"
      
      
    },
    {
      id:13,
      imgUrl: "./assets/image/ff.jpg",
      name: "Alex Zoo",
      address: "Porto Blvd, Suite 100 Los Angeles/CA",
      phone: 12345678910,
      email: "Zooo@mail.com",
      addressUrl: "(view directions)",
      locImg: "./assets/image/pin.png",
      animals:"Lions",
      sliderimage1:"./assets/image/s7.jpg",
      sliderimage2:"./assets/image/s5.jpg",
      sliderimage3:"./assets/image/s4.jpg",
      description:"The biggest zoo in egypt has alot of animals like lions ...",
      showimg:"./assets/image/show.jpg",
      showdescription:"Visita il Delfinario di Dubai per ammirare i graziosi delfini dal naso a bottiglia e le foche che giocano durante gli spettacoli d'animazione. Scegli tra il biglietto standard e quello VIP...",
      showname:"splach safari show",
      upshowdescription:"In the heart of the Burmese rainforest is where some elephants feel right at home. In this unique show, uncover the rare sight of these magnificent animals at work and play in their rainforest habitat alongside their mahouts.",
      upshowname:"Elephants at Work and Play Show",
      upshowdate:"5:00 PM",
      showdate:"6:00 PM",
      upshowloc:"Egypt",
      showloc:"Egypt",
      newsname:"Wild Animals Go Missing at a Zoo, Stirring Fears",
      newsdescription:"The animals briefly slipped their enclosures after heavy flooding at a German zoo — prompting a call for residents to stay indoors. One animal, a bear, was shot dead.",
      newsimg:"./assets/image/news.jpg",
      writer:"JOHN DOE",
      newsdate:" NOV 18",
      newsname1:"Wild Animals Go Missing at a Zoo, Stirring Fears",
      newsdescription1:"The animals briefly slipped their enclosures after heavy flooding at a German zoo — prompting a call for residents to stay indoors. One animal, a bear, was shot dead.",
      newsimg1:"./assets/image/news1.jpg",
      writer1:"JOHN DOE",
      newsdate1:" NOV 19",
      newsname2:"Wild Animals Go Missing at a Zoo, Stirring Fears",
      newsdescription2:"The animals briefly slipped their enclosures after heavy flooding at a German zoo — prompting a call for residents to stay indoors. One animal, a bear, was shot dead.",
      newsimg2:"./assets/image/news2.jpg",
      writer2:"JOHN DOE",
      newsdate2:" NOV 20"
      
      
    },
    {
      id:14,
      imgUrl: "./assets/image/aa.jpg",
      name: "Tunis Zoo ",
      address: "Porto Blvd, Suite 100 Los Angeles/CA",
      phone: 12345678910,
      email: "Zooo@mail.com",
      addressUrl: "(view directions)",
      locImg: "./assets/image/pin.png",
      animals:"Monkey",
      sliderimage1:"./assets/image/s2.jpg",
      sliderimage2:"./assets/image/s1.jpg",
      sliderimage3:"./assets/image/s3.jpg",
      description:"The biggest zoo in egypt has alot of animals like lions ...",
      showimg:"./assets/image/event1.jpg",
      showdescription:"Visita il Delfinario di Dubai per ammirare i graziosi delfini dal naso a bottiglia e le foche che giocano durante gli spettacoli d'animazione. Scegli tra il biglietto standard e quello VIP...",
      showname:"splach safari show",
      upshowdescription:"In the heart of the Burmese rainforest is where some elephants feel right at home. In this unique show, uncover the rare sight of these magnificent animals at work and play in their rainforest habitat alongside their mahouts.",
      upshowname:"Elephants at Work and Play Show",
      upshowdate:"5:00 PM",
      showdate:"6:00 PM",
      upshowloc:"Egypt",
      showloc:"Egypt",
      newsname:"Wild Animals Go Missing at a Zoo, Stirring Fears",
      newsdescription:"The animals briefly slipped their enclosures after heavy flooding at a German zoo — prompting a call for residents to stay indoors. One animal, a bear, was shot dead.",
      newsimg:"./assets/image/news4.jpg",
      writer:"JOHN DOE",
      newsdate:" NOV 18",
      newsname1:"Wild Animals Go Missing at a Zoo, Stirring Fears",
      newsdescription1:"The animals briefly slipped their enclosures after heavy flooding at a German zoo — prompting a call for residents to stay indoors. One animal, a bear, was shot dead.",
      newsimg1:"./assets/image/news5.jpg",
      writer1:"JOHN DOE",
      newsdate1:" NOV 19",
      newsname2:"Wild Animals Go Missing at a Zoo, Stirring Fears",
      newsdescription2:"The animals briefly slipped their enclosures after heavy flooding at a German zoo — prompting a call for residents to stay indoors. One animal, a bear, was shot dead.",
      newsimg2:"./assets/image/news3.jpg",
      writer2:"JOHN DOE",
      newsdate2:" NOV 20"
      
      
    },
    {
      id:15,
      imgUrl: "./assets/image/aa.jpg",
      name: "lebia Zoo ",
      address: "Porto Blvd, Suite 100 Los Angeles/CA",
      phone: 12345678910,
      email: "Zooo@mail.com",
      addressUrl: "(view directions)",
      locImg: "./assets/image/pin.png",
      animals:"Cheetas",
      sliderimage1:"./assets/image/s7.jpg",
      sliderimage2:"./assets/image/s5.jpg",
      sliderimage3:"./assets/image/s4.jpg",
      description:"The biggest zoo in egypt has alot of animals like lions ...",
      showimg:"./assets/image/event1.jpg",
      showdescription:"Visita il Delfinario di Dubai per ammirare i graziosi delfini dal naso a bottiglia e le foche che giocano durante gli spettacoli d'animazione. Scegli tra il biglietto standard e quello VIP...",
      showname:"splach safari show",
      upshowdescription:"In the heart of the Burmese rainforest is where some elephants feel right at home. In this unique show, uncover the rare sight of these magnificent animals at work and play in their rainforest habitat alongside their mahouts.",
      upshowname:"Elephants at Work and Play Show",
      upshowdate:"5:00 PM",
      showdate:"6:00 PM",
      upshowloc:"Egypt",
      showloc:"Egypt",
      newsname:"Wild Animals Go Missing at a Zoo, Stirring Fears",
      newsdescription:"The animals briefly slipped their enclosures after heavy flooding at a German zoo — prompting a call for residents to stay indoors. One animal, a bear, was shot dead.",
      newsimg:"./assets/image/news.jpg",
      writer:"JOHN DOE",
      newsdate:" NOV 18",
      newsname1:"Wild Animals Go Missing at a Zoo, Stirring Fears",
      newsdescription1:"The animals briefly slipped their enclosures after heavy flooding at a German zoo — prompting a call for residents to stay indoors. One animal, a bear, was shot dead.",
      newsimg1:"./assets/image/news1.jpg",
      writer1:"JOHN DOE",
      newsdate1:" NOV 19",
      newsname2:"Wild Animals Go Missing at a Zoo, Stirring Fears",
      newsdescription2:"The animals briefly slipped their enclosures after heavy flooding at a German zoo — prompting a call for residents to stay indoors. One animal, a bear, was shot dead.",
      newsimg2:"./assets/image/news2.jpg",
      writer2:"JOHN DOE",
      newsdate2:" NOV 20"
      
      
    },
    {
      id:16,
      imgUrl: "./assets/image/aa.jpg",
      name: "Brazil Zoo",
      address: "Porto Blvd, Suite 100 Los Angeles/CA",
      phone: 12345678910,
      email: "Zooo@mail.com",
      addressUrl: "(view directions)",
      locImg: "./assets/image/pin.png",
      animals:"Zebras",
      sliderimage1:"./assets/image/s7.jpg",
      sliderimage2:"./assets/image/s5.jpg",
      sliderimage3:"./assets/image/s4.jpg",
      description:"The biggest zoo in egypt has alot of animals like lions ...",
      showimg:"./assets/image/event1.jpg",
      showdescription:"Visita il Delfinario di Dubai per ammirare i graziosi delfini dal naso a bottiglia e le foche che giocano durante gli spettacoli d'animazione. Scegli tra il biglietto standard e quello VIP...",
      showname:"splach safari show",
      upshowdescription:"In the heart of the Burmese rainforest is where some elephants feel right at home. In this unique show, uncover the rare sight of these magnificent animals at work and play in their rainforest habitat alongside their mahouts.",
      upshowname:"Elephants at Work and Play Show",
      upshowdate:"5:00 PM",
      showdate:"6:00 PM",
      upshowloc:"Egypt",
      showloc:"Egypt",
      newsname:"Wild Animals Go Missing at a Zoo, Stirring Fears",
      newsdescription:"The animals briefly slipped their enclosures after heavy flooding at a German zoo — prompting a call for residents to stay indoors. One animal, a bear, was shot dead.",
      newsimg:"./assets/image/news5.jpg",
      writer:"JOHN DOE",
      newsdate:" NOV 18",
      newsname1:"Wild Animals Go Missing at a Zoo, Stirring Fears",
      newsdescription1:"The animals briefly slipped their enclosures after heavy flooding at a German zoo — prompting a call for residents to stay indoors. One animal, a bear, was shot dead.",
      newsimg1:"./assets/image/news4.jpg",
      writer1:"JOHN DOE",
      newsdate1:" NOV 19",
      newsname2:"Wild Animals Go Missing at a Zoo, Stirring Fears",
      newsdescription2:"The animals briefly slipped their enclosures after heavy flooding at a German zoo — prompting a call for residents to stay indoors. One animal, a bear, was shot dead.",
      newsimg2:"./assets/image/news6.jpg",
      writer2:"JOHN DOE",
      newsdate2:" NOV 20"
      
      
    },
    {
      id:17,
      imgUrl: "./assets/image/aa.jpg",
      name: "Giza Zoo",
      address: "Porto Blvd, Suite 100 Los Angeles/CA",
      phone: 12345678910,
      email: "Zooo@mail.com",
      addressUrl: "(view directions)",
      locImg: "./assets/image/pin.png",
      animals:"Horses",
      sliderimage1:"./assets/image/s7.jpg",
      sliderimage2:"./assets/image/s5.jpg",
      sliderimage3:"./assets/image/s4.jpg",
      description:"The biggest zoo in egypt has alot of animals like lions ...",
      showimg:"./assets/image/event1.jpg",
      showdescription:"Visita il Delfinario di Dubai per ammirare i graziosi delfini dal naso a bottiglia e le foche che giocano durante gli spettacoli d'animazione. Scegli tra il biglietto standard e quello VIP...",
      showname:"splach safari show",
      upshowdescription:"In the heart of the Burmese rainforest is where some elephants feel right at home. In this unique show, uncover the rare sight of these magnificent animals at work and play in their rainforest habitat alongside their mahouts.",
      upshowname:"Elephants at Work and Play Show",
      upshowdate:"5:00 PM",
      showdate:"6:00 PM",
      upshowloc:"Egypt",
      showloc:"Egypt",
      newsname:"Wild Animals Go Missing at a Zoo, Stirring Fears",
      newsdescription:"The animals briefly slipped their enclosures after heavy flooding at a German zoo — prompting a call for residents to stay indoors. One animal, a bear, was shot dead.",
      newsimg:"./assets/image/news6.jpg",
      writer:"JOHN DOE",
      newsdate:" NOV 18",
      newsname1:"Wild Animals Go Missing at a Zoo, Stirring Fears",
      newsdescription1:"The animals briefly slipped their enclosures after heavy flooding at a German zoo — prompting a call for residents to stay indoors. One animal, a bear, was shot dead.",
      newsimg1:"./assets/image/news3.jpg",
      writer1:"JOHN DOE",
      newsdate1:" NOV 19",
      newsname2:"Wild Animals Go Missing at a Zoo, Stirring Fears",
      newsdescription2:"The animals briefly slipped their enclosures after heavy flooding at a German zoo — prompting a call for residents to stay indoors. One animal, a bear, was shot dead.",
      newsimg2:"./assets/image/news1.jpg",
      writer2:"JOHN DOE",
      newsdate2:" NOV 20"
      
      
    },
    {
      id:18,
      imgUrl: "./assets/image/aa.jpg",
      name: "Cairo Zoo",
      address: "Porto Blvd, Suite 100 Los Angeles/CA",
      phone: 12345678910,
      email: "Zooo@mail.com",
      addressUrl: "(view directions)",
      locImg: "./assets/image/pin.png",
      animals:"Fishes",
      sliderimage1:"./assets/image/s7.jpg",
      sliderimage2:"./assets/image/s5.jpg",
      sliderimage3:"./assets/image/s4.jpg",
      description:"The biggest zoo in egypt has alot of animals like lions ...",
      showimg:"./assets/image/event1.jpg",
      showdescription:"Visita il Delfinario di Dubai per ammirare i graziosi delfini dal naso a bottiglia e le foche che giocano durante gli spettacoli d'animazione. Scegli tra il biglietto standard e quello VIP...",
      showname:"splach safari show",
      upshowdescription:"In the heart of the Burmese rainforest is where some elephants feel right at home. In this unique show, uncover the rare sight of these magnificent animals at work and play in their rainforest habitat alongside their mahouts.",
      upshowname:"Elephants at Work and Play Show",
      upshowdate:"5:00 PM",
      showdate:"6:00 PM",
      upshowloc:"Egypt",
      showloc:"Egypt",
      newsname:"Wild Animals Go Missing at a Zoo, Stirring Fears",
      newsdescription:"The animals briefly slipped their enclosures after heavy flooding at a German zoo — prompting a call for residents to stay indoors. One animal, a bear, was shot dead.",
      newsimg:"./assets/image/news.jpg",
      writer:"JOHN DOE",
      newsdate:" NOV 18",
      newsname1:"Wild Animals Go Missing at a Zoo, Stirring Fears",
      newsdescription1:"The animals briefly slipped their enclosures after heavy flooding at a German zoo — prompting a call for residents to stay indoors. One animal, a bear, was shot dead.",
      newsimg1:"./assets/image/news1.jpg",
      writer1:"JOHN DOE",
      newsdate1:" NOV 19",
      newsname2:"Wild Animals Go Missing at a Zoo, Stirring Fears",
      newsdescription2:"The animals briefly slipped their enclosures after heavy flooding at a German zoo — prompting a call for residents to stay indoors. One animal, a bear, was shot dead.",
      newsimg2:"./assets/image/news2.jpg",
      writer2:"JOHN DOE",
      newsdate2:" NOV 20"
      
      
    },
    {
      id:19,
      imgUrl: "./assets/image/aa.jpg",
      name: "london Zoo",
      address: "Porto Blvd, Suite 100 Los Angeles/CA",
      phone: 12345678910,
      email: "Zooo@mail.com",
      addressUrl: "(view directions)",
      locImg: "./assets/image/pin.png",
      animals:"Tortoise",
      sliderimage1:"./assets/image/s7.jpg",
      sliderimage2:"./assets/image/s5.jpg",
      sliderimage3:"./assets/image/s4.jpg",
      description:"The biggest zoo in egypt has alot of animals like lions ...",
      showimg:"./assets/image/show1.jpg",
      showdescription:"Visita il Delfinario di Dubai per ammirare i graziosi delfini dal naso a bottiglia e le foche che giocano durante gli spettacoli d'animazione. Scegli tra il biglietto standard e quello VIP...",
      showname:"splach safari show",
      upshowdescription:"In the heart of the Burmese rainforest is where some elephants feel right at home. In this unique show, uncover the rare sight of these magnificent animals at work and play in their rainforest habitat alongside their mahouts.",
      upshowname:"Elephants at Work and Play Show",
      upshowdate:"5:00 PM",
      showdate:"6:00 PM",
      upshowloc:"Egypt",
      showloc:"Egypt",
      newsname:"Wild Animals Go Missing at a Zoo, Stirring Fears",
      newsdescription:"The animals briefly slipped their enclosures after heavy flooding at a German zoo — prompting a call for residents to stay indoors. One animal, a bear, was shot dead.",
      newsimg:"./assets/image/news.jpg",
      writer:"JOHN DOE",
      newsdate:" NOV 18",
      newsname1:"Wild Animals Go Missing at a Zoo, Stirring Fears",
      newsdescription1:"The animals briefly slipped their enclosures after heavy flooding at a German zoo — prompting a call for residents to stay indoors. One animal, a bear, was shot dead.",
      newsimg1:"./assets/image/news1.jpg",
      writer1:"JOHN DOE",
      newsdate1:" NOV 19",
      newsname2:"Wild Animals Go Missing at a Zoo, Stirring Fears",
      newsdescription2:"The animals briefly slipped their enclosures after heavy flooding at a German zoo — prompting a call for residents to stay indoors. One animal, a bear, was shot dead.",
      newsimg2:"./assets/image/news2.jpg",
      writer2:"JOHN DOE",
      newsdate2:" NOV 20"
      
      
    },
  ];
  topzoos: IZooSmallComponent[]= [ {
    id:1,
    imgUrl: "./assets/image/aa.jpg",
    name: "LosAngeles",
    address: "Porto Blvd, Suite 100 Los Angeles/CA",
    phone: 12345678910,
    email: "Zooo@mail.com",
    addressUrl: "(view directions)",
    locImg: "./assets/image/pin.png",
    animals:"Giraffes"
  },
  {
    id:2,
    imgUrl: "./assets/image/dd.jpg",
    name: "Gizaa Zoo",
    address: "Porto Blvd, Suite 100 Los Angeles/CA",
    phone: 12345678910,
    email: "Zooo@mail.com",
    addressUrl: "(view directions)",
    locImg: "./assets/image/pin.png",
    animals:"Elephants"

  },
  {
    id:3,
    imgUrl: "./assets/image/ff.jpg",
    name: "Alex Zoo",
    address: "Porto Blvd, Suite 100 Los Angeles/CA",
    phone: 12345678910,
    email: "Zooo@mail.com",
    addressUrl: "(view directions)",
    locImg: "./assets/image/pin.png",
    animals:"Lions"
  },
  {
    id:4,
    imgUrl: "./assets/image/aa.jpg",
    name: "Ismailia ",
    address: "Porto Blvd, Suite 100 Los Angeles/CA",
    phone: 12345678910,
    email: "Zooo@mail.com",
    addressUrl: "(view directions)",
    locImg: "./assets/image/pin.png",
    animals:"Monkey"
  },
  {
    id:5,
    imgUrl: "./assets/image/aa.jpg",
    name: "Portsaid ",
    address: "Porto Blvd, Suite 100 Los Angeles/CA",
    phone: 12345678910,
    email: "Zooo@mail.com",
    addressUrl: "(view directions)",
    locImg: "./assets/image/pin.png",
    animals:"Cheetas"
  },
  {
    id:6,
    imgUrl: "./assets/image/aa.jpg",
    name: "Portsaid ",
    address: "Porto Blvd, Suite 100 Los Angeles/CA",
    phone: 12345678910,
    email: "Zooo@mail.com",
    addressUrl: "(view directions)",
    locImg: "./assets/image/pin.png",
    animals:"Zebras"
  },
  {
    id:7,
    imgUrl: "./assets/image/aa.jpg",
    name: "elwadyelgded",
    address: "Porto Blvd, Suite 100 Los Angeles/CA",
    phone: 12345678910,
    email: "Zooo@mail.com",
    addressUrl: "(view directions)",
    locImg: "./assets/image/pin.png",
    animals:"Horses"
  },
  {
    id:8,
    imgUrl: "./assets/image/aa.jpg",
    name: "Cairo ",
    address: "Porto Blvd, Suite 100 Los Angeles/CA",
    phone: 12345678910,
    email: "Zooo@mail.com",
    addressUrl: "(view directions)",
    locImg: "./assets/image/pin.png",
    animals:"Fishes"
  },
  {
    id:8,
    imgUrl: "./assets/image/aa.jpg",
    name: "elswees ",
    address: "Porto Blvd, Suite 100 Los Angeles/CA",
    phone: 12345678910,
    email: "Zooo@mail.com",
    addressUrl: "(view directions)",
    locImg: "./assets/image/pin.png",
    animals:"Tortoise"
  },
];
  constructor() { }
  getZooSmallComponent(): IZooSmallComponent[] {
    return this.zoos;
  }

  getzoo(id){
    return this.zoos.find(zoo => zoo.id == id);
  }

 deletezoo(id){
    var zoo = this.zoos.map(function(item) { return item.id; }).indexOf(id);
    this.zoos.splice(zoo, 1);
  }
  addZoo(form) {
    var zoo: IZooSmallComponent;
    zoo = form.value;
    zoo.imgUrl="./assets/image/aa.jpg"
    zoo.locImg="./assets/image/pin.png"
    this.zoos.push(zoo);
  }
  public getZoos() {
    return this.zoos;
  }
  public getTopZoos() {
    return this.zoos;
  }
}
